DDDのベースのアーキテクチャを追加
ispec-inc/starry pull request #9
Opened 2023-07-05 08:37 UTC by yamad07

2023-07-05 22:25 UTC, mokoshin0720 requested changes
いくつか質問と消し忘れっぽいところにコメントしました！！

2023-07-05 22:25 UTC, mokoshin0720 commented on packages/api-go-ddd-graphql/service/clinic/internal/domain/id_test.go
> +			t.Parallel()
あ、テーブル駆動で書く時はfor文の中にも`t.Parallel()`書かないとダメだったんですね、、、知らんかった、、、（[zenn](https://zenn.dev/takokun/articles/b3722a89851fb0)見た）

2023-07-05 22:25 UTC, mokoshin0720 commented on packages/api-go-ddd-graphql/service/clinic/internal/domain/organization/organization.go
> +type Organization struct {
これドキュメントの方にもコメントしたんですが、値オブジェクトにもコメントを書くべきかどうか検討したいです！！！

2023-07-05 22:25 UTC, mokoshin0720 commented on packages/api-go-ddd-graphql/service/clinic/internal/domain/organization/organization.go
> +type OrganizationType int
個人的には値オブジェクトの定義＆メソッドは別ファイルに切り出した方が可読性上がるのではと思っているんですが、いかがでしょう、、、？
値オブジェクトのメソッドも1つのファイルにまとめると、このファイルの行数がとんでもないことになりそうだなと、、、

2023-07-05 22:25 UTC, mokoshin0720 commented on packages/api-go-ddd-graphql/service/clinic/internal/domain/organization/organization.go
> +type OrganizationType int
というか、`phone_number.go`は切り離されていそう

2023-07-05 22:25 UTC, mokoshin0720 commented on packages/api-go-ddd-graphql/service/clinic/internal/infra/reader/organization.go
> +	// MySQL DB
これはコメント消し忘れですかね、、？

2023-07-05 22:25 UTC, mokoshin0720 commented on packages/api-go-ddd-graphql/service/clinic/internal/infra/reader/organization.go
> +// idsが空の場合は全件取得する
（全件取得事件懐かしい）

今回の実装では問題ないと思うんですけど、このクエリを参考に実装を進めていくとなると、idsが空の時はDBアクセスせずに早期returnする例を置いておく方が事件発生しなさそうな気もしました😶‍🌫️

2023-07-05 22:25 UTC, mokoshin0720 commented on packages/api-go-ddd-graphql/service/clinic/internal/uc/get_organization.go
> +	tx := g.db.Begin()
これ調べても明確な情報が出てこなかったので質問になっちゃんですが、今回のようにtransactionを貼らなくても問題ないケースに対してもtransactionを貼ることによるデメリットって何かありますかね、、、？

「脳死ですべてのクエリにtransaction貼っちゃっても良いのかな？」ってなってました🤔

2023-07-06 13:01 UTC, yamad07 commented on packages/api-go-ddd-graphql/service/clinic/internal/domain/organization/organization.go
> +type Organization struct {
exportedなものは全て書く想定！

https://github.com/ispec-inc/design-doc/pull/2#discussion_r1254401356

2023-07-06 13:01 UTC, yamad07 commented on packages/api-go-ddd-graphql/cmd/db/seed/main.go
> +	// db, err := app.MySQL()
修正！

[599c30f](https://github.com/ispec-inc/starry/pull/9/commits/599c30fb0df5cc93e318804d23a2f404464e65a2)

2023-07-06 13:01 UTC, yamad07 commented on packages/api-go-ddd-graphql/app/gqlerror/gqlerror_test.go
> +// func TestError_Error(t *testing.T) {
修正！

[599c30f](https://github.com/ispec-inc/starry/pull/9/commits/599c30fb0df5cc93e318804d23a2f404464e65a2)

2023-07-06 23:12 UTC, mokoshin0720 reviewed
🍚 !!!

2023-07-06 23:12 UTC, mokoshin0720 commented on packages/api-go-ddd-graphql/app/gqlerror/gqlerror_test.go
> +// func TestError_Error(t *testing.T) {
お、、、消せてなさそうかもです🥺(130行目に同じテストがあるので、多分削除になるかなと🙆🏻‍♂️)

2023-07-06 23:12 UTC, mokoshin0720 commented on packages/api-go-ddd-graphql/service/clinic/internal/domain/organization/organization.go
> +type Organization struct {
なるほどです！
そしたらフィールド（IDやName）へのコメントはどうしましょうか、、？

一応かなちーさんから貰っていた意見としては、フィールドにもあった方がキャッチアップはしやすそうかなという気はしています🙆🏻‍♂️

2023-07-07 00:07 UTC, yamad07 commented on packages/api-go-ddd-graphql/app/gqlerror/gqlerror_test.go
> +// func TestError_Error(t *testing.T) {
あ、追加だけして削除してなかった、あざす！

[fix: delete](https://github.com/ispec-inc/starry/pull/9/commits/8bc4259784db204df715d7d2734b382d8934b194)

2023-07-07 00:07 UTC, yamad07 commented on packages/api-go-ddd-graphql/service/clinic/internal/domain/organization/organization.go
> +type Organization struct {
ああ、そうだね、それも書こう！
ただこれ、完全にlintで弾いてくれる想定なんだけど関数かstructしか弾いてくれないのか、、
これは人力レビューしかないのか、ちょっと色々考えるわ

[46d77c7](https://github.com/ispec-inc/starry/pull/9/commits/46d77c722e1d33d461454c44ad9ab034f275e357)

2023-07-11 01:34 UTC, mokoshin0720 approved these changes
![LGTM](https://image.lgtmoon.dev/214891)

2023-07-11 01:36 UTC, merged